name: Upload Python Package

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    # if this is a release, upload to PyPI
    - name: Build and publish release
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
